### ISSUE TITLE
Scaling up publish instances should pause not disable

### ISSUE THREAD

**Issue by ryancurrah** [shinesolutions/aem-orchestrator#31]
Hey, first off thanks for open sourcing a lot of your tools! They have been very helpful in my quest to automate scaling AEM6 publish servers in Google Cloud with HashiCorp Consul.

I am opening this issue in reference to the scale up publish event.

During a scale up publish event [step 4](https://github.com/shinesolutions/aem-orchestrator/blob/master/docs/scale-up-events.md#scale-up-publish) takes a healthy publish agent and and pauses it in the replication queue. This is to make sure no changes get pushed to the healthy publish agent during the snapshot. 

The issue I found when I looked at the method [getPauseReplicationAgentRequest](https://github.com/shinesolutions/aem-orchestrator/blob/b3e16ac12c2cae6f92a0e8cca221aafcc482f485/src/main/java/com/shinesolutions/aemorchestrator/aem/AgentRequestFactory.java#L129) which pauses the healthy publish agent. Is that it disables the publish agent instead of pausing it. Wouldn't this cause the healthy publish instance to miss any updates that were published during the snapshot? Or is there a process that prevents users from publishing during a scale up publish event that I am not seeing?

Thanks again for sharing your great work with the community,
Ry

**Comment by cliffano** [comment]
@ryancurrah Thanks for checking them out!

I'm glad to hear that you're using it in GCP because that validates our design to ensure that the tools are modular enough that they can be reused in various settings, in this case, various cloud service providers.

As for getPauseReplicationAgentRequest. The intention was to ensure that there will be no content that get published to the healthy snapshot, however, if there's a piece of content that gets published from the author, it will be added to the agent's queue but it won't be published due to authentication failure using the invalid user. Is this different to what you're seeing?

Which AEM version are you using?
This practice of fake pausing by setting invalid user was carried over from older versions of AEM where pausing feature didn't actually work. I would like to get a better idea whether this is now working 100% with the newer version of AEM.

**Comment by ryancurrah** [comment]
Hey thanks for the quick reply. I did not know about the pause workaround, I learned something today.

I am currently doing a proof of concept with Adobe AEM 6.3.0 Cumulative Fix Pack 2.0. And no the pause feature still does not work correctly! :( 

If I use the configuration the function `getPauseReplicationAgentRequest` sets on the healthy publish agent which is setting `enable` to `false` and changes the `transportUser` to an invalid user. Any changes published do not get placed in the replication queue for that agent. 

For the this to work on AEM 6.3.0.2  if I only change the username to an invalid name and leave the agent enabled it works as you describe. The published items queue up and when I changed the user back to a valid user the published items get replicated to the healthy publish agent.

So I'm not sure if this is something specific to AEM 6.3.0.2 or earlier I don't have an older instance to test with.

**Comment by cliffano** [comment]
Thanks for confirming that pause feature still doesn't work in 6.3.0 + CFP 2 :), this is exactly valuable information that I would like to hear from wider AEM community.

I see, so your test indicates that `getPauseReplicationAgentRequest` should keep the fake transportUser approach, but instead of setting `enable` to `false`, it should set it to `true`.
Now that you describe it in details, IIRC, I also think that agent should still be enabled. So this could be a bug or a mixed up scenario during our integration testing.

I'll verify it with AEM 6.2 and will get back to you.

**Comment by cliffano** [comment]
Done. This will be included in version 1.0.1 .
Thanks again @ryancurrah for notifying us about this. Much appreciated.
